services:
  blog-db:
    image: mysql
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.dbwala == true
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-h'
        - localhost
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_password
    volumes:
      - blog-db-vol:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - blog-app-net
    secrets:
      - db_password
  blog-server:
    image: ptlvaibhav/blog-demo-app:build-5c8196250e71695c1e5446103ddac7a83c08ea96
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
    healthcheck:
      test:
        - CMD
        - wget
        - '--no-verbose'
        - '--tries=1'
        - '--spider'
        - http://localhost:3000/health
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=blog-db
      - DB_USER_FILE=/run/secrets/db_username
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - DB_NAME=blogdb
      - NODE_HOST="{{.Node.Hostname}}"
    networks:
      - blog-app-net
    secrets:
      - db_password
      - db_username
  caddy:
    image: caddy:2-alpine
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - blog-app-net
    configs:
      - source: Caddyfile
        target: /etc/caddy/Caddyfile
  db-backup:
    image: fradelg/mysql-cron-backup:latest
    environment:
      - MYSQL_HOST=blog-db
      - MYSQL_USER_FILE=/run/secrets/db_username
      - MYSQL_PASS_FILE=/run/secrets/db_password
      - MAX_BACKUPS=15
      - INIT_BACKUP=1
      - CRON_TIME=* * * * *
      - GZIP_LEVEL=9
      - EXIT_BACKUP=1
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.dbwala == true
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
    volumes:
      - mysql_backup:/backup
    networks:
      - blog-app-net
    secrets:
      - db_password
      - db_username
volumes:
  blog-db-vol: null
  caddy_data: null
  caddy_config: null
  mysql_backup: null
networks:
  blog-app-net: null
secrets:
  db_password:
    external: true
  db_username:
    external: true
configs:
  Caddyfile:
    file: ./Caddyfile
